services:

  muse:
    build: .
    container_name: Muse
    depends_on:
      - keycloak
      - postgres-spring
    environment:
      DB_URL: postgres-spring:5432/muse
      ISSUER_URI: http://keycloak:8080/realms/users-auth
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - maven:/root/.m2
    ports:
      - "80:8080"
    command: mvn spring-boot:run

  keycloak:
    container_name: Keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: root
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      KEYCLOAK_HOSTNAME: keycloak
      KC_HOSTNAME: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - postgres-keycloak
    volumes:
      - ./keycloak/users-auth-realm.json:/opt/keycloak/data/import/realm-export.json
    command:
      [
        'start-dev',
        '--import-realm',
        '--http-enabled=true',
      ]

  postgres-spring:
    container_name: Postgres-spring
    image: postgres
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: boot
      POSTGRES_DB: muse
    ports:
      - 5432:5432

  postgres-keycloak:
    container_name: Postgres-keycloak
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  postgres_keycloak_data:
    driver: local
  maven:
    driver: local
  keycloak:
    driver: local