services:

  muse:
    build: .
    container_name: Muse
    depends_on:
      - keycloak
      - postgres-spring
    environment:
      DB_URL: postgres-spring:5432/muse
      ISSUER_URI: http://keycloak:8080/realms/users-auth
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - maven:/root/.m2
    ports:
      - "80:8080"
    command: mvn spring-boot:run

  keycloak:
    container_name: Keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: root
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      KEYCLOAK_HOSTNAME: keycloak
      KC_HOSTNAME: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - postgres-keycloak
    volumes:
      - ./keycloak/users-auth-realm.json:/opt/keycloak/data/import/realm-export.json
    command:
      [
        'start-dev',
        '--import-realm',
        '--http-enabled=true',
      ]

  postgres-spring:
    container_name: Postgres-spring
    image: postgres
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: boot
      POSTGRES_DB: muse
    ports:
      - 5432:5432

  postgres-keycloak:
    container_name: Postgres-keycloak
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,DOCKER://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,DOCKER://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_keycloak_data:
    driver: local
  maven:
    driver: local
  keycloak:
    driver: local