spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/muse}?stringtype=unspecified
    username: spring
    password: boot
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migrations,classpath:db/testdata
    validate-on-migrate: true
    out-of-order: false
  security:
    cors: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/users-auth
  messages:
    basename: messages
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
logging:
  level:
    org.springframework.security: TRACE
