spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/muse}?stringtype=unspecified
    username: ${DB_USER:spring}
    password: ${DB_PASSWORD:boot}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migrations
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 1
    out-of-order: false
  security:
    cors: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  data:
    web:
      pageable:
        max-page-size: 30
  messages:
    basename: messages
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /api
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true