ALTER TABLE posts
ALTER COLUMN created TYPE TIMESTAMPTZ USING created AT TIME ZONE 'UTC',
ALTER COLUMN updated TYPE TIMESTAMPTZ USING updated AT TIME ZONE 'UTC';

ALTER TABLE comments
ALTER COLUMN created TYPE TIMESTAMPTZ USING created AT TIME ZONE 'UTC',
ALTER COLUMN updated TYPE TIMESTAMPTZ USING updated AT TIME ZONE 'UTC';

ALTER TABLE votes
ALTER COLUMN created TYPE TIMESTAMPTZ USING created AT TIME ZONE 'UTC';
